apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubesphere-iam-validator
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: <caBundle>
      service:
        name: ks-controller-manager
        namespace: kubesphere-system
        path: /validate-email-iam-kubesphere-io-v1alpha2
    failurePolicy: Fail
    name: vemail.iam.kubesphere.io
    rules:
      - apiGroups:
          - iam.kubesphere.io
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - users